const { sql } = require('./db');

const schemaSQL = `
-- 1. Buat Tabel Categories (Kategori Belanja)
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Buat Tabel Items / Products (Produk Belanja)
CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price NUMERIC(12, 2) NOT NULL DEFAULT 0,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  image_url TEXT,
  stock INT DEFAULT 0,
  is_available BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Trigger otomatis update timestamp updated_at pada items
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS update_items_updated_at ON items;
CREATE TRIGGER update_items_updated_at
BEFORE UPDATE ON items
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
`;

async function runMigration() {
  if (!sql) {
    console.log('⚠️ DATABASE_URL belum diatur di file .env.');
    console.log('👉 Untuk menjalankan migrasi SQL langsung dari Node.js, tambahkan connection string Supabase ke .env:');
    console.log('   DATABASE_URL=postgresql://postgres:[PASSWORD]@db.ldkrtvlhygvnlyhrfdcw.supabase.co:5432/postgres\n');
    console.log('--- ATAU COPY PASTE QUERY INI KE SUPABASE DASHBOARD -> SQL EDITOR ---');
    console.log(schemaSQL);
    return;
  }

  try {
    console.log('🚀 Menjalankan migrasi skema SQL ke database Supabase...');
    await sql.unsafe(schemaSQL);
    console.log('✅ Skema tabel "categories" dan "items" berhasil dibuat di Supabase!');
  } catch (error) {
    console.error('❌ Gagal menjalankan migrasi skema:', error.message);
  } finally {
    await sql.end();
  }
}

if (require.main === module) {
  runMigration();
}

module.exports = {
  schemaSQL,
  runMigration,
};
